// <auto-generated />
namespace WebMotors.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class remove_required_observacao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_required_observacao));
        
        string IMigrationMetadata.Id
        {
            get { return "201904300623553_remove_required_observacao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
